supertokens/supertokens-core

README.md, cli/src/main/java/io/supertokens/cli/commandHandler/install/InstallHandler.java, cli/src/main/resources/install-linux.sh, cli/src/main/resources/install-windows.bat
This commit adds a trap mechanism around the exec call to pass the signals received by bash to a child process.
Due to added complexity and for better legibility, I've opted to move the source for both scripts from java to a resource.
These changes are based on [sigterm propagation](http://veithen.io/2014/11/16/sigterm-propagation.html).
I was not able to test the changes in their full extent, due to compilation issues on this project, I did however successfully test the change by overriding via volume mounts in docker. Let me know if this breaks windows compatibility or doesn't work after a full build.
=> Add trap mechanism to handle term signals. Fixes #28

src/main/java/io/supertokens/emailpassword/EmailPassword.java, src/main/java/io/supertokens/webserver/api/emailpassword/UserAPI.java
Replace getUserUsingUsingId() to getUserUsingId() and getUserUsingUsingEmail() to getUserUsingEmail()
No issue
Was going through the code, then I notice typo
yes
I only change the method name. And after that, I was able to create build successfully, So that's how I test it.
Test cases are no longer required, as it is a typo issue.
(If this PR adds or changes functionality, please take some time to point to the relevant documentation that we should update -  https://supertokens.io/docs/community/getting-started/installation)
=> Fix typo in method name

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/jwt/JWTSigningFunctions.java, src/test/java/io/supertokens/test/jwt/JWTCreateTest.java
In the JWT recipe when creating a JWT the core would always add the apiDomain as the `iss` claim in the payload (overwriting any value that the user would send). This PR changes the logic to do that only if there is no value already provided for the `iss` claim.
NA
NA
=> Add iss claim only if it is missing

CHANGELOG.md, config.yaml, devConfig.yaml, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/webserver/Webserver.java, src/test/java/io/supertokens/test/WebserverTest.java
Adds `base_path` config so that users can set a custom base path for all API requests. This allows for a feature like https://github.com/supertokens/supertokens-node/issues/252
- https://github.com/supertokens/supertokens-node/issues/252
Added unit tests
=> adds base_path config

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/Start.java, src/test/java/io/supertokens/test/InMemoryDBTest.java
- Catching `StorageTransactionLogicException` in transaction helper function for retries.
- Added a new test in PostgreSQL plugin which uses passwordless recipe to simulate a deadlock which should be retried
- https://github.com/supertokens/supertokens-core/issues/373
- Added a new test
=> fixes: Takes into account StorageTransactionLogicException when doing retries in transaction

CHANGELOG.md, cli/src/main/java/io/supertokens/cli/Main.java, src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/output/CustomLayout.java, src/main/java/io/supertokens/output/LayoutWrappingEncoder.java, src/main/java/io/supertokens/output/Logging.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/test/java/io/supertokens/test/APIKeysTest.java, src/test/java/io/supertokens/test/AuthRecipeTest.java, src/test/java/io/supertokens/test/InMemoryDBStorageTest.java, src/test/java/io/supertokens/test/InMemoryDBTest.java, src/test/java/io/supertokens/test/LoggingTest.java, src/test/java/io/supertokens/test/StorageTest.java, src/test/java/io/supertokens/test/Utils.java, src/test/java/io/supertokens/test/session/AccessTokenTest.java
We do not destroy the storage layer between tests unless required. This speeds up each test run.
```
13 Mar 2022 03:47:04:312 +0530 | ERROR | pid: 3c5fb9d8-3020-4d54-b7f1-7130165d623c | [pool-873-thread-5] thread | io.supertokens.storage.sql.HibernateLoggingAppender.doAppend(HibernateLoggingAppender.java:132) | HikariDataSource HikariDataSource (SuperTokens) has been closed.
13 Mar 2022 03:47:04:313 +0530 | ERROR | pid: 3c5fb9d8-3020-4d54-b7f1-7130165d623c | [pool-873-thread-4] thread | io.supertokens.storage.sql.HibernateLoggingAppender.doAppend(HibernateLoggingAppender.java:132) | HikariDataSource HikariDataSource (SuperTokens) has been closed.
13 Mar 2022 03:47:04:315 +0530 | ERROR | pid: 3c5fb9d8-3020-4d54-b7f1-7130165d623c | [pool-873-thread-3] thread | …
```
=> Test optimisation to reuse storage layer

CHANGELOG.md, cli/src/main/java/io/supertokens/cli/processes/Processes.java, src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/config/CoreConfig.java, src/test/java/io/supertokens/test/DotStartedFileTest.java, src/test/java/io/supertokens/test/WebserverTest.java
`supertokens list` previously failed when `base_path` was set in `config.yaml` due to a GET request by the CLI that did not observe `base_path`. I added the base path of the server to the .started file in addition to the PID so that the CLI can GET the /config route without encountering 404 errors.
- Modifies .started file to include the base_path of the server in addition to the PID
- Ensures that the CLI reads this value in order to correctly query the server to get the config file location
- Changes config validation to gracefully handle leading and trailing '/'
- Updates CHANGELOG.md
- Adds relevant tests
- Closes #408
- Replaces #409 
- Modified `DotStartedFileTest.java` to test the new .started file structure
- Modified `WebserverTest.java` to remove the now irrelevant `base_path` …
=> fix: SuperTokens list ignoring base_path in config

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/UserRoleQueries.java, src/main/java/io/supertokens/userroles/UserRoles.java, src/test/java/io/supertokens/test/userRoles/UserRolesStorageTest.java
- The `addPermissionToRole_Transaction` in the plugin-interface has been changed to `addPermissionToRoleOrDoNothingIfExists_Transaction` this PR reflects that change in the core
- https://github.com/supertokens/supertokens-plugin-interface/pull/35
- Testing for these functions already exist
- none
=> fix: renames addPermissionToRole function

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/UserRoleQueries.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/api/userroles/AddUserRoleAPI.java, src/test/java/io/supertokens/test/userRoles/UserRolesStorageTest.java, src/test/java/io/supertokens/test/userRoles/UserRolesTest.java, src/test/java/io/supertokens/test/userRoles/api/AddUserRoleAPITest.java
Refactors AddUserRole API in the `user-roles` base branch + fixs. Adds tests for AddUserRole API related functions.
- https://github.com/supertokens/supertokens-core/pull/414
- ~~[ ] Changelog has been updated~~
- ~~[ ] If there are any DB schema changes, mention those changes clearly~~
- ~~[ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)~~
- ~~[ ] `pluginInterfaceSupported.json` file has been updated (if needed)~~
- ~~[ ] Changes to the version if needed~~
- ~~[ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in …
=> feat: AddUserRole api

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/UserRoleQueries.java, src/main/java/io/supertokens/userroles/UserRoles.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/api/userroles/RemovePermissionsForRoleAPI.java, src/test/java/io/supertokens/test/userRoles/UserRolesStorageTest.java, src/test/java/io/supertokens/test/userRoles/UserRolesTest.java, src/test/java/io/supertokens/test/userRoles/api/RemovePermissionsForRoleAPITest.java
Adds RemovePermissionFromRoleAPI, core functions, and inmemory db queries
- https://github.com/supertokens/supertokens-core/pull/414
- none
=> feat: adds RemovePermissionsFromRoleAPI + tests

CHANGELOG.md, build.gradle
the failing tests are collected and printed
after the test suite completes execution
which helps in finding failing tests easily
when running from CLI
=> build: print failing test at the end

CHANGELOG.md, src/test/java/io/supertokens/test/passwordless/api/PasswordlessDeleteCodeAPITest2_11.java
Changes the way codeId is generated for Passwordless test
since the columns are char based, we should always supply exact length data
NA
NA
NA
NA
=> fix: code id generation for PasswordlessCode Test

CHANGELOG.md, README.md, src/main/java/io/supertokens/session/accessToken/AccessToken.java, src/main/java/io/supertokens/session/info/SessionInformationHolder.java, src/main/java/io/supertokens/utils/Utils.java, src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionRegenerateAPI.java, src/main/java/io/supertokens/webserver/api/session/VerifySessionAPI.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest2_7.java, src/test/java/io/supertokens/test/session/api/SessionAPITest2_9.java, src/test/java/io/supertokens/test/session/api/SessionDataAPITest2_7.java, src/test/java/io/supertokens/test/session/api/SessionRegenerateAPITest2_7.java, src/test/java/io/supertokens/test/session/api/VerifySessionAPITest2_9.java
Fixes handling of nulls in access token payload
- #499 
- Added a separate test in session token creation
- Updated other tests that check if access token payload is kept consistent
N/A, bugfix
=> fix: null props in access token

CHANGELOG.md
The MySQL statement was duplicated. For Postgres `ALTER COLUMN` must be used instead of `MODIFY`
=> fix: correct db migration statement for postgres

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/config/CoreConfig.java, src/test/java/io/supertokens/test/jwt/JWTCreateTest.java, src/test/java/io/supertokens/test/session/SessionTest4.java
Updates `access_token_validity` from `int` to `long`
- https://github.com/supertokens/supertokens-core/issues/534
=> fix: updates access token type

src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionRemoveAPI.java
Supress usermapping exceptions for active users monitoring
- https://github.com/supertokens/supertokens-core/pull/586
=> fix: Suppress usermapping exceptions for active users monitoring

src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest2_19.java
make refresh api return unauthorised on AccessTokenPayloadError
- 
Updated existing test
N/A
=> feat: make refresh api return unauthorised on AccessTokenPayloadError

src/test/java/io/supertokens/test/ActiveUsersTest.java, src/test/java/io/supertokens/test/emailpassword/api/SignInAPITest2_7.java, src/test/java/io/supertokens/test/emailpassword/api/SignUpAPITest2_7.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest2_7.java, src/test/java/io/supertokens/test/session/api/SessionRemoveAPITest2_7.java
Add delay to flake Active users tests
=> test: Add delay to flake Active users tests

src/main/java/io/supertokens/emailpassword/EmailPassword.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/test/java/io/supertokens/test/emailpassword/DeleteExpiredPasswordResetTokensCronjobTest.java, src/test/java/io/supertokens/test/emailpassword/EmailPasswordTest.java, src/test/java/io/supertokens/test/emailpassword/api/ImportUserWithPasswordHashAPITest.java, src/test/java/io/supertokens/test/emailpassword/api/SignUpAPITest2_7.java
=> fix: Multitenant emailpassword

src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/useridmapping/UserIdMapping.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/main/java/io/supertokens/webserver/api/useridmapping/UserIdMappingAPI.java, src/test/java/io/supertokens/test/emailpassword/MultitenantEmailPasswordTest.java, src/test/java/io/supertokens/test/userIdMapping/UserIdMappingTest.java, src/test/java/io/supertokens/test/userIdMapping/api/MultitenantAPITest.java
- Disallow same external userid across all storages
- Prioritize tenant of interest while working with appIdentifierWithStorage
- https://github.com/supertokens/supertokens-core/issues/610 (not addressed)
=> fix: Multitenant user id mapping tests

CHANGELOG.md, src/main/java/io/supertokens/signingkeys/JWTSigningKey.java, src/test/java/io/supertokens/test/jwt/JWTCreateTest.java
fix: fix getting jwt signing keys with MongoDB (already existing in master)
Added test that creates 2 JWTs, ensuring we have a key created before we sign the second one
N/A
=> fix: fix getting jwt signing keys with mongodb

src/main/java/io/supertokens/session/Session.java, src/main/java/io/supertokens/session/accessToken/AccessToken.java, src/main/java/io/supertokens/session/accessToken/AccessTokenSigningKey.java, src/main/java/io/supertokens/session/refreshToken/RefreshToken.java, src/main/java/io/supertokens/session/refreshToken/RefreshTokenKey.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/main/java/io/supertokens/webserver/api/session/HandshakeAPI.java, src/main/java/io/supertokens/webserver/api/session/JWTDataAPI.java, src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionDataAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionRegenerateAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionRemoveAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionUserAPI.java, src/main/java/io/supertokens/webserver/api/session/VerifySessionAPI.java, src/test/java/io/supertokens/test/InMemoryDBStorageTest.java, src/test/java/io/supertokens/test/InMemoryDBTest.java, src/test/java/io/supertokens/test/StorageTest.java, src/test/java/io/supertokens/test/multitenant/SigningKeysTest.java, src/test/java/io/supertokens/test/session/AccessTokenSigningKeyTest.java, src/test/java/io/supertokens/test/session/AccessTokenTest.java, src/test/java/io/supertokens/test/session/DeleteExpiredAccessTokenSigningKeysTest.java, src/test/java/io/supertokens/test/session/RegenerateTokenTest.java, src/test/java/io/supertokens/test/session/SessionTest1.java, src/test/java/io/supertokens/test/session/SessionTest2.java, src/test/java/io/supertokens/test/session/SessionTest3.java, src/test/java/io/supertokens/test/session/SessionTest4.java, src/test/java/io/supertokens/test/session/api/MultitenantAPITest.java
=> fix: Multitenant session

src/main/java/io/supertokens/signingkeys/JWTSigningKey.java, src/test/java/io/supertokens/test/session/AccessTokenSigningKeyTest.java
disable jwt signing key generation if testing to test legacy key migration in mongo
=> test: disable jwt signing key generation if testing to test legacy key migration in mongo

src/main/java/io/supertokens/session/Session.java, src/main/java/io/supertokens/session/accessToken/AccessToken.java, src/main/java/io/supertokens/webserver/api/session/JWTDataAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionDataAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionRegenerateAPI.java, src/test/java/io/supertokens/test/session/SessionGetSessionDataTest.java, src/test/java/io/supertokens/test/session/SessionTest4.java, src/test/java/io/supertokens/test/session/api/HandshakeAPITest2_21.java, src/test/java/io/supertokens/test/session/api/JWTDataAPITest2_21.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest2_21.java, src/test/java/io/supertokens/test/session/api/SessionRegenerateAPITest2_21.java
- Checking for protected props in JWTDataAPI to make sure it can't break a session
- Added the same checks for other endpoints - it's more consistent, and it makes sure that the changes do not get saved in the DB
- We still need the check when serializing the access tokens to ensure. The above checks are mainly for user convenience that is more about security.
- To …
=> fix: throw if a protected prop is passed to JWTDataAPI

.gitignore, CHANGELOG.md, build.gradle, implementationDependencies.json, src/main/java/io/supertokens/jwt/JWTSigningFunctions.java, src/test/java/io/supertokens/test/session/api/SessionAPITest2_21.java
- updated dependency version for java-jwt
- fixed an issue during access token serialization
- 
Extended existing test
N/A
=> fix: exp and iat should not use exponential format in the access token

CHANGELOG.md, src/main/java/io/supertokens/dashboard/Dashboard.java, src/test/java/io/supertokens/test/dashboard/apis/CreateDashboardUserAPITests.java, src/test/java/io/supertokens/test/dashboard/apis/GetDashboardUsersAPITests.java
=> fix: Updates free dashboard user count

src/test/java/io/supertokens/test/TestingProcessManager.java, src/test/java/io/supertokens/test/multitenant/LogTest.java, src/test/java/io/supertokens/test/multitenant/api/TestLicenseBehaviour.java, src/test/java/io/supertokens/test/multitenant/api/TestMultitenancyAPIHelper.java
Tests for License behaviour when it is removed from a core that has multiple tenants.
- Blocks tenant creation, thirdparty config creation and user association
- Server restart loads all tenants correctly
latest branch (`git branch --all`) …
=> fix: License tests

src/test/java/io/supertokens/test/totp/TOTPRecipeTest.java, src/test/java/io/supertokens/test/totp/api/VerifyTotpAPITest.java
=> test: Improve TOTP tests

config.yaml, devConfig.yaml, src/main/java/io/supertokens/config/CoreConfig.java
In config.yaml (for core and plugins) + devConfig.yaml, we should add a comment against each config saying DIFFERENT_ACROSS_TENANTS or DIFFERENT_ACROSS_APPS. since in the docs, we say to lookout for this comment to know which config can be different per tenant.
Recheck core constraint that can be different across tenant IDs + make sure that check that they can be different across app IDs. …
=> fix: config per tenant, per app annotations and validation

src/test/java/io/supertokens/test/oauth2/StorageTests.java
Added test to verify working of `createOAuth2Client_Transaction` psql implementation
- https://github.com/supertokens/supertokens-core/issues/582
=> Added tests for create method

src/main/java/io/supertokens/webserver/api/core/UsersAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/ImportUserWithPasswordHashAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/SignInAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/SignUpAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/UserAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/ConsumeCodeAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/UserAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/GetUsersByEmailAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/SignInUpAPI.java
Removing `tenantIds` from user object when CDI version < 3.0
=> fix: not adding tenantids in old version

src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/cronjobs/syncCoreConfigWithDb/SyncCoreConfigWithDb.java, src/test/java/io/supertokens/test/CronjobTest.java
=> fix: cronjob to sync config from db

src/main/java/io/supertokens/webserver/Utils.java
=> fix: cud regex

src/main/java/io/supertokens/config/CoreConfig.java, src/test/java/io/supertokens/test/CLIOptionsTest.java, src/test/java/io/supertokens/test/CronjobTest.java, src/test/java/io/supertokens/test/TelemetryTest.java, src/test/java/io/supertokens/test/multitenant/AppTenantUserTest.java, src/test/java/io/supertokens/test/multitenant/api/TestApp.java, src/test/java/io/supertokens/test/multitenant/api/TestConnectionUriDomain.java, src/test/java/io/supertokens/test/multitenant/api/TestSkipValidationInCreateThirdParty.java, src/test/java/io/supertokens/test/multitenant/api/TestTenant.java, src/test/java/io/supertokens/test/session/RefreshTokenTest.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest2_7.java
=> fix: Test fixes

config.yaml, devConfig.yaml, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/CDIVersionTest.java, src/test/java/io/supertokens/test/multitenant/ConfigTest.java
=> fix: Default CDI version per app

src/main/java/io/supertokens/webserver/Utils.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/multitenant/api/TestPermissionChecks.java
=> fix: use invalid cud as default cud

src/test/java/io/supertokens/test/multitenant/api/TestApp.java, src/test/java/io/supertokens/test/multitenant/api/TestConnectionUriDomain.java
=> fix: inmemory test fix

CHANGELOG.md, src/main/java/io/supertokens/webserver/api/core/NotFoundOrHelloAPI.java, src/test/java/io/supertokens/test/HelloAPITest.java
Hello API / not found should not throw `Invalid API key`
=> fix: hello or not found api should not throw invalid API key

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java, src/main/java/io/supertokens/inmemorydb/queries/ThirdPartyQueries.java, src/test/java/io/supertokens/test/authRecipe/MultitenantAPITest.java
- https://github.com/supertokens/supertokens-node/pull/471
=> fix: users search queries

CHANGELOG.md, config.yaml, devConfig.yaml, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/utils/SemVer.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/main/java/io/supertokens/webserver/api/core/ApiVersionAPI.java, src/main/java/io/supertokens/webserver/api/multitenancy/CreateOrUpdateTenantOrGetTenantAPI.java, src/test/java/io/supertokens/test/CDIVersionTest.java, src/test/java/io/supertokens/test/multitenant/ConfigTest.java
=> fix: multitenancy and version related

src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/CDIVersionTest.java
=> fix: tests

src/test/java/io/supertokens/test/PathRouterTest.java
=> fix: test fix

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/jwt/JWTSigningFunctions.java, src/test/java/io/supertokens/test/session/AccessTokenTest.java
Now using decimal notation to add numbers into the access token payload (instead of scientific notation)
- 
Updated inputOutput tests to check the expiration time format
N/A
=> fix: add exp and iat to JWT payloads without scientific notation

src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/main/java/io/supertokens/authRecipe/UserPaginationContainer.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/webserver/api/core/UsersAPI.java, src/test/java/io/supertokens/test/AuthRecipeTest.java, src/test/java/io/supertokens/test/authRecipe/GetUsersWithSearchTagsTest.java
=> fix: user pagination changes

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/utils/Utils.java, src/test/java/io/supertokens/test/session/AccessTokenTest.java
fix handling of b64 and b64url encoded access tokens
- Issues in prod logs
Updated existing tests to highlight differences between encodings
N/A, bugfix
=> fix: fix handling of b64 and b64url encoded access tokens

src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/main/java/io/supertokens/authRecipe/exception/RecipeUserIdAlreadyLinkedWithAnotherPrimaryUserIdException.java, src/main/java/io/supertokens/webserver/api/accountlinking/CanLinkAccountsAPI.java, src/main/java/io/supertokens/webserver/api/accountlinking/LinkAccountsAPI.java, src/main/java/io/supertokens/webserver/api/core/ListUsersByAccountInfoAPI.java, src/test/java/io/supertokens/test/accountlinking/DeleteUserTest.java, src/test/java/io/supertokens/test/accountlinking/LinkAccountsTest.java, src/test/java/io/supertokens/test/accountlinking/api/CanLinkAccountsAPITest.java, src/test/java/io/supertokens/test/accountlinking/api/GetUserByAccountInfoTest.java, src/test/java/io/supertokens/test/accountlinking/api/LinkAccountsAPITest.java, src/test/java/io/supertokens/test/authRecipe/GetUserByIdAPITest.java
- Link account should return the updated user object in status OK
- linkAccount should return the updated user object in status `RECIPE_USER_ID_ALREADY_LINKED_WITH_ANOTHER_PRIMARY_USER_ID_ERROR`
latest branch (`git branch --all`) whose `X.Y` is greater …
=> fix: user object in link accounts api

src/main/java/io/supertokens/passwordless/Passwordless.java, src/main/java/io/supertokens/thirdparty/ThirdParty.java, src/main/java/io/supertokens/webserver/api/passwordless/ConsumeCodeAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/SignInUpAPI.java, src/test/java/io/supertokens/test/passwordless/api/EmailVerificationTest.java, src/test/java/io/supertokens/test/thirdparty/api/EmailVerificationTest.java
=> fix: emailverified in tp & pless

CHANGELOG.md, build.gradle, ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/main/java/io/supertokens/Main.java, src/test/java/io/supertokens/test/CronjobTest.java, src/test/java/io/supertokens/test/FeatureFlagTest.java
=> fix: ee featureflag cron job

src/main/java/io/supertokens/emailpassword/EmailPassword.java, src/main/java/io/supertokens/passwordless/Passwordless.java, src/main/java/io/supertokens/thirdparty/ThirdParty.java, src/test/java/io/supertokens/test/emailpassword/api/EmailPasswordGetUserAPITest2_7.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessUserGetAPITest2_11.java, src/test/java/io/supertokens/test/thirdparty/api/ThirdPartyGetUserAPITest2_7.java
=> fix: get user by id as per recipe

CHANGELOG.md
=> fix: fkey constraint on primary_or_recipe_user_id

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/137
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/139 …
=> fix: link and unlink accounts

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/141
=> fix: password reset changes

src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/144
=> fix: fixes query

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java, src/main/java/io/supertokens/inmemorydb/queries/ThirdPartyQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/147
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/149 …
=> fix: multitenant user association

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/inmemorydb/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java, src/main/java/io/supertokens/inmemorydb/queries/ThirdPartyQueries.java
=> fix: remove con reuse

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/154
=> fix: account linking stats

CHANGELOG.md, build.gradle, ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, ee/src/test/java/io/supertokens/ee/test/TestMultitenancyStats.java, ee/src/test/java/io/supertokens/ee/test/Utils.java
=> fix: stats fix

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/passwordless/Passwordless.java, src/main/java/io/supertokens/passwordless/PasswordlessDeviceIdHash.java, src/main/java/io/supertokens/passwordless/PasswordlessLinkCode.java, src/test/java/io/supertokens/test/passwordless/PasswordlessConsumeCodeTest.java
- linkCodes and preAuthSessionIds should not use padding (= signs)
- we should accept them with and without = signs
- Issue reported on discord about some router clearing `=` signs from query params
- Added new test that removes all '=' signs from linkcodes and preauthsessionids and checks that it remains the same (plus it still works)
- Added new test that adds '=' signs to linkcodes and preauthsessionids and checks that it sign in still works.
We can update some example data, but we do not document the format in detail
- If no such …
=> feat: linkcodes and preauthsessionids should not use padding

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/passwordless/Passwordless.java, src/test/java/io/supertokens/test/accountlinking/EmailPasswordTests.java
- https://github.com/supertokens/supertokens-core/issues/828
=> fix: passwordless login fix

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/cronjobs/Cronjobs.java, src/test/java/io/supertokens/test/CronjobTest.java
Task shouldn't be scheduled to executor if the task already exists in the tasks list.
Manually tested that right number of API calls is being done. Couldn't find a way to count number of scheduled executors.
=> fix: duplicate cron task

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/TOTPQueries.java, src/main/java/io/supertokens/totp/Totp.java, src/main/java/io/supertokens/webserver/api/totp/ImportTotpDeviceAPI.java, src/test/java/io/supertokens/test/StorageLayerTest.java, src/test/java/io/supertokens/test/totp/TOTPStorageTest.java, src/test/java/io/supertokens/test/totp/api/CreateTotpDeviceAPITest.java, src/test/java/io/supertokens/test/totp/api/ImportTotpDeviceAPITest.java, src/test/java/io/supertokens/test/totp/api/MultitenantAPITest.java, src/test/java/io/supertokens/test/totp/api/TotpUserIdMappingTest.java, src/test/java/io/supertokens/test/totp/api/VerifyTotpAPITest.java, src/test/java/io/supertokens/test/totp/api/VerifyTotpDeviceAPITest.java
- https://github.com/supertokens/supertokens-core/pull/651 …
=> fix: add createdat to totp device

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/passwordless/Passwordless.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/thirdparty/ThirdParty.java, src/main/java/io/supertokens/useridmapping/UserIdMapping.java, src/main/java/io/supertokens/webserver/api/useridmapping/UserIdMappingAPI.java, src/test/java/io/supertokens/test/emailverification/EmailVerificationWithUserIdMappingTest.java, src/test/java/io/supertokens/test/multitenant/AppTenantUserTest.java
We automatically set email as verified for passwordless users and thirdparty user when the user info from provider has isVerified set to true. This blocks us from creating useridmapping. So we allow creating of useridmapping and update the userid for email verification to the external user id.
- To know which one it is, run find the latest released tag (`git tag`) …
=> fix: email verification fix with user id mapping

src/test/java/io/supertokens/test/UtilsTest.java
This is a continuation of #881. This just improves one of the test cases for `normaliseIfPhoneNumber` util function.
https://github.com/supertokens/supertokens-core/issues/880
=> feat: Improve test for invalid phone number inputs

CHANGELOG.md, build.gradle, implementationDependencies.json, migration_scripts/to_version_7_0_12/.gitignore, migration_scripts/to_version_7_0_12/index.js, migration_scripts/to_version_7_0_12/package-lock.json, migration_scripts/to_version_7_0_12/package.json, src/main/java/io/supertokens/utils/Utils.java, src/main/java/io/supertokens/webserver/api/core/ListUsersByAccountInfoAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/CreateCodeAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/DeleteCodesAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/GetCodesAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/UserAPI.java, src/test/java/io/supertokens/test/UtilsTest.java, src/test/java/io/supertokens/test/accountlinking/api/GetUserByAccountInfoTest.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessCreateCodeAPITest.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessDeleteCodesAPITest.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessGetCodesAPITest.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessUserGetAPITest.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessUserPutAPITest.java
This PR introduces phone number normalisation to all API endpoints that accept phone numbers as user input. The implementation includes the addition of a `normaliseIfPhoneNumber` function in the `Utils` class, which is now utilized across all relevant APIs.
This PR also introduces phone number normalisation migration script that is supposed to be run on the all the core instances after migrating to version 7.0.12.
See #881 , #882 
- https://github.com/supertokens/supertokens-core/issues/880
- Tests are added for the `normaliseIfPhoneNumber` util function
- Tests are added for every API that changed
- Migration script was tested manual 200K rows for both PostgreSQL and MySQL databases
- To know which one it is, run find the latest …
=> feat: Normalise phoneNumber received in the input before processing + Migration script 

src/main/java/io/supertokens/passwordless/Passwordless.java, src/main/java/io/supertokens/webserver/api/passwordless/ConsumeCodeAPI.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessConsumeCodeAPITest5_0.java
- https://github.com/supertokens/supertokens-core/pull/651 …
=> fix: createNewRecipeUser input in consume code API

CHANGELOG.md, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java, src/main/java/io/supertokens/session/Session.java, src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/test/java/io/supertokens/test/StorageTest.java, src/test/java/io/supertokens/test/session/SessionTest6.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest2_21.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest5_0.java, src/test/java/io/supertokens/test/session/api/SessionRegenerateAPITest2_21.java
- Add a `useDynamicSigningKey` param to the refresh session api (v5.0+). This matches the parameter name used by the session creation API.
- Use the above param to update the `useStaticSigningKey` of the session during refresh. 
- core: https://github.com/supertokens/supertokens-core/pull/909
- plugin-interface: https://github.com/supertokens/supertokens-plugin-interface/pull/136
- postgresql-plugin: https://github.com/supertokens/supertokens-postgresql-plugin/pull/180
- mysql-plugin: https://github.com/supertokens/supertokens-mysql-plugin/pull/88
- mongodb-plugin: https://github.com/supertokens/supertokens-mongodb-plugin/pull/31
- node: https://github.com/supertokens/supertokens-node/pull/782
- Added tests to API output while switching  
- successOutputSwitchingWithStaticKeySessionTest
- …
=> feat: make refresh sync signing key setting

src/main/java/io/supertokens/totp/Totp.java, src/main/java/io/supertokens/webserver/api/totp/ImportTotpDeviceAPI.java, src/test/java/io/supertokens/test/totp/api/ImportTotpDeviceAPITest.java
=> fix: totp import api

src/main/java/io/supertokens/emailpassword/EmailPassword.java, src/main/java/io/supertokens/utils/Utils.java, src/main/java/io/supertokens/webserver/api/emailpassword/SignUpAPI.java, src/test/java/io/supertokens/test/emailpassword/api/SignUpAPITest5_0.java
=> fix: Fake email verified for emailpassword sign up

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/output/Logging.java
Fixes issue where error logs were printed to StdOut instead of StdErr.
=> fix: error logs should be printed to StdErr

CHANGELOG.md, build.gradle, config.yaml, devConfig.yaml, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/multitenancy/MultitenancyHelper.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/main/java/io/supertokens/webserver/api/multitenancy/BaseCreateOrUpdate.java, src/test/java/io/supertokens/test/PathRouterTest.java, src/test/java/io/supertokens/test/TestGetUserSpeed.java, src/test/java/io/supertokens/test/multitenant/ConfigTest.java, src/test/java/io/supertokens/test/multitenant/LoadOnlyCUDTest.java
=> fix: load only cud config in core

CHANGELOG.md, build.gradle, cli/build.gradle, ee/build.gradle, implementationDependencies.json, src/main/java/io/supertokens/cronjobs/telemetry/Telemetry.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/SignInAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/SignUpAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/ConsumeCodeAPI.java, src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionRemoveAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/SignInUpAPI.java, src/test/java/io/supertokens/test/ActiveUsersTest.java, src/test/java/io/supertokens/test/TelemetryTest.java
- https://github.com/supertokens/supertokens-core/issues/926
=> fix: Vulnerability fix

src/main/java/io/supertokens/passwordless/Passwordless.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/api/passwordless/CheckCodeAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/DeleteCodeAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/VerifyCodeAPI.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessCheckCodeAPITest5_0.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessDeleteCodeAPITest5_0.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessVerifyCodeAPITest5_0.java
=> fix: add check code API and update delete code API

src/main/java/io/supertokens/session/Session.java, src/test/java/io/supertokens/test/accountlinking/api/ActiveUserTest.java, src/test/java/io/supertokens/test/multitenant/api/TestApp.java
=> fix: cicd test

CHANGELOG.md, src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest3_0.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest5_0.java
feat: backport useDynamicSigningKey in refresh api
- 
Added tests:
- with and without the new prop in V3
- without new prop in V5
- 
=> feat: backport useDynamicSigningKey in refresh api

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/ActiveUsers.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java, src/main/java/io/supertokens/inmemorydb/queries/UserIdMappingQueries.java, src/main/java/io/supertokens/session/Session.java, src/main/java/io/supertokens/useridmapping/UserIdMapping.java, src/main/java/io/supertokens/webserver/api/accountlinking/LinkAccountsAPI.java, src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/test/java/io/supertokens/test/AuthRecipeTest.java, src/test/java/io/supertokens/test/accountlinking/SessionTests.java, src/test/java/io/supertokens/test/authRecipe/UserPaginationTest.java, src/test/java/io/supertokens/test/session/SessionTest6.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest3_0.java, src/test/java/io/supertokens/test/session/api/SessionRegenerateAPITest2_21.java, src/test/java/io/supertokens/test/userIdMapping/UserIdMappingStorageTest.java
=> fix: backports to core 7.0

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java, src/main/java/io/supertokens/inmemorydb/queries/UserIdMappingQueries.java, src/main/java/io/supertokens/session/Session.java, src/main/java/io/supertokens/useridmapping/UserIdMapping.java, src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/test/java/io/supertokens/test/AuthRecipeTest.java, src/test/java/io/supertokens/test/authRecipe/UserPaginationTest.java, src/test/java/io/supertokens/test/session/SessionTest6.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest3_0.java, src/test/java/io/supertokens/test/session/api/SessionRegenerateAPITest2_21.java, src/test/java/io/supertokens/test/userIdMapping/UserIdMappingStorageTest.java
=> fix: backport to core 6.0

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/test/java/io/supertokens/test/multitenant/LogTest.java
=> fix: backport 8.0.3

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/test/java/io/supertokens/test/accountlinking/LinkAccountsTest.java
fix: make canLinkAccountsHelper check if the login methods of the primary user have conflicts on the tenant of the link target
- 
Added an extra test-case
N/A
the user as well if `deleteUserIdMappingToo` is false.
=> fix: make canLinkAccountsHelper check if the login methods of the primary user have conflicts on the tenant of the link target

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java
Adds index for MAU
- https://github.com/supertokens/supertokens-core/issues/994
- If no such branch exists, then create one from …
=> fix: index for MAU

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/webserver/api/multitenancy/BaseCreateOrUpdate.java, src/test/java/io/supertokens/test/multitenant/api/TestApp5_1.java, src/test/java/io/supertokens/test/multitenant/api/TestConnectionUriDomain5_1.java, src/test/java/io/supertokens/test/multitenant/api/TestTenant5_1.java
=> fix: validating firstFactors not to contain special chars

CHANGELOG.md, build.gradle, cli/src/main/java/io/supertokens/cli/commandHandler/start/StartHandler.java, src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/cliOptions/CLIOptions.java, src/main/java/io/supertokens/webserver/Webserver.java, src/test/java/io/supertokens/test/CLIOptionsTest.java, src/test/java/io/supertokens/test/DotStartedFileTest.java, src/test/java/io/supertokens/test/WebserverTest.java
Adds support in CLI and in Core to specify the temp folder location. It's required for docker when run with readonly root fs.
[1048](https://github.com/supertokens/supertokens-core/issues/1048)
latest branch (`git …
=> fix: docker readonly fs

CHANGELOG.md, src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/cronjobs/cleanupOAuthRevokeListAndChallenges/CleanupOAuthSessionsAndChallenges.java, src/main/java/io/supertokens/inmemorydb/PreparedStatementValueSetter.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/config/SQLiteConfig.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/OAuthQueries.java, src/main/java/io/supertokens/oauth/OAuth.java, src/main/java/io/supertokens/oauth/OAuthToken.java, src/main/java/io/supertokens/webserver/api/oauth/OAuthAcceptAuthConsentRequestAPI.java, src/main/java/io/supertokens/webserver/api/oauth/OAuthAuthAPI.java, src/main/java/io/supertokens/webserver/api/oauth/OAuthTokenAPI.java, src/main/java/io/supertokens/webserver/api/oauth/OAuthTokenIntrospectAPI.java, src/main/java/io/supertokens/webserver/api/oauth/RevokeOAuthTokenAPI.java, src/test/java/io/supertokens/test/oauth/OAuthStorageTest.java, src/test/java/io/supertokens/test/oauth/api/TestAuthCodeFlow.java, src/test/java/io/supertokens/test/oauth/api/TestIssueTokens.java, src/test/java/io/supertokens/test/oauth/api/TestRefreshTokenFlowWithTokenRotationOptions.java, src/test/java/io/supertokens/test/oauth/api/TestRevoke5_2.java
Allow listing instead of revoke listing the tokens. …
=> feat: oauth/allow list

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/OAuthQueries.java, src/main/java/io/supertokens/oauth/OAuth.java, src/main/java/io/supertokens/webserver/api/oauth/OAuthAuthAPI.java, src/main/java/io/supertokens/webserver/api/oauth/OAuthTokenAPI.java, src/test/java/io/supertokens/test/multitenant/TestAppData.java, src/test/java/io/supertokens/test/oauth/OAuthStorageTest.java
Changing how the commas are handled in the jti list. Changing method signature from List<String> to String
latest branch (`git branch --all`) whose `X.Y` is greater than the …
=> fix: jti listing in db

.circleci/config.yml, .circleci/doTests.sh, CHANGELOG.md, src/main/java/io/supertokens/oauth/Transformations.java
- make deep links work
- fix changelog consistency
- add parallelism and make re-running failed tests easier
latest branch (`git branch --all`) whose `X.Y` is greater than …
=> feat: make deep links work

src/test/java/io/supertokens/test/bulkimport/BulkImportFlowTest.java, src/test/java/io/supertokens/test/bulkimport/apis/AddBulkImportUsersTest.java
=> fix: fix AddBulkImportUsersTest

src/test/java/io/supertokens/test/bulkimport/ProcessBulkImportUsersCronJobTest.java, src/test/java/io/supertokens/test/emailpassword/PasswordHashingTest.java
This would give me an indication about the ci/tests issues cause. If the build is successful without these tests, it would narrow down where to search for the root. After discovering what causing the issues on ci, these tests should be turned back on.
Also, there are timing refinements in an other test, which is sometimes failing because of timing issues.
config …
=> experiment: turn off problematic tests

CHANGELOG.md, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java
The lack of index on `session_info`'s `(app_id, user_id)` was causing performance issues at one of the users, so here it goes.
latest branch (`git branch --all`) whose `X.Y` …
=> fix: add index for session_info on user_id, app_id

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/bulkimport/BulkImport.java, src/test/java/io/supertokens/test/bulkimport/BulkImportTestUtils.java
This changes the Bulk Migraitons behavior by actually using the `isVerified` field's value from the input when doing the email verification.
latest branch (`git branch …
=> fix: bulk migration to actually use the input value for the email verification

CHANGELOG.md, src/main/java/io/supertokens/cronjobs/bulkimport/ProcessBulkUsersImportWorker.java
NPE fix when externalUserId is null
- If no such branch exists, then create one from …
=> fix: bulk import external userid error translation

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/bulkimport/BulkImport.java, src/test/java/io/supertokens/test/bulkimport/apis/ImportUserTest.java
=> fix: bulk migration user to roles association in case of non primary user

.github/workflows/container-check.yml
=> fix: container security check cron
