cli/src/main/resources/install-windows.bat
Closes #50.
Removed code is not relevant anymore.
Yes
=> Removed update part from the install.bat script

src/main/java/io/supertokens/emailpassword/EmailPassword.java, src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java, src/main/java/io/supertokens/webserver/api/emailpassword/UserAPI.java
Providing flexibility
yes
I have refactor the existing functionality. No new functionality has been added.
(If this PR adds or changes functionality, please take some time to point to the relevant documentation that we should update -  https://supertokens.io/docs/community/getting-started/installation)
=> Row mapper impl

src/main/java/io/supertokens/session/Session.java
Spotted a small typo while checking the source code.
Yes.
=> Fix typo in comment

CHANGELOG.md
Typo fix in changelog. 4.0.0 --> 3.3.0
=> fixes typo in changelog

config.yaml, devConfig.yaml, src/main/java/io/supertokens/config/CoreConfig.java
=> Adding passwordless related config options

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/config/SQLiteConfig.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/test/java/io/supertokens/test/passwordless/PasswordlessStorageTest.java
Adding in-memory implementation for the passwordless plugin-interface
- #321 
- supertokens/supertokens-plugin-interface#27
=> Adding inmemory implementation for the passwordless plugin-interface

src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/passwordless/Passwordless.java, src/main/java/io/supertokens/passwordless/PasswordlessDeviceId.java, src/main/java/io/supertokens/passwordless/PasswordlessDeviceIdHash.java, src/main/java/io/supertokens/passwordless/PasswordlessLinkCode.java, src/main/java/io/supertokens/passwordless/PasswordlessLinkCodeHash.java, src/main/java/io/supertokens/passwordless/exceptions/ExpiredUserInputCodeException.java, src/main/java/io/supertokens/passwordless/exceptions/IncorrectUserInputCodeException.java, src/main/java/io/supertokens/utils/Utils.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/api/passwordless/ConsumeCodeAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/CreateCodeAPI.java, src/test/java/io/supertokens/test/AuthRecipeTest.java, src/test/java/io/supertokens/test/passwordless/PasswordlessStorageTest.java, src/test/java/io/supertokens/test/passwordless/PasswordlessTest.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessConsumeCodeAPITest2_10.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessCreateCodeAPITest2_10.java
Adding consume code API
- #322 
- #333 
Added some of the basic testcases the rest will be collected on the passwordless->version branch PR.
=> Passwordless consume code

.github/ISSUE_TEMPLATE/release.md, README.md
Updates to read me and release template
=> updates readme and pr template

README.md
Added SuperTokens website link to the head banner of the readme. 
```
[![SuperTokens banner](https://raw.githubusercontent.com/supertokens/supertokens-logo/master/images/Artboard%20%E2%80%93%2027%402x.png)](https://supertokens.com/)
```
=> Update README 'added website link to banner image'

README.md
A concise description to help the repo visitors understand quickly what Supertokens is
=> README update: Concise project description on the top

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java
Updated for new plugin interface version ( using lower transaction isolation level for createDeviceWithCode)
- https://github.com/supertokens/supertokens-plugin-interface/pull/30
N/A
N/A
=> feat: updated for new plugin interface version

.github/workflows/tests.yml, CHANGELOG.md, CONTRIBUTING.md
TODO
- https://github.com/supertokens/for-zenhub/issues/100
=> ci: Adds action for tests

.github/helpers/.gitignore, .github/helpers/package.json, .github/helpers/test-pass-check-pr.js, .github/workflows/tests-pass-check-pr.yml, CHANGELOG.md
- https://github.com/supertokens/for-zenhub/issues/100
=> ci: Tests pass gh action

CHANGELOG.md, src/test/java/io/supertokens/test/Utils.java
=> fix: replacing of config during tests

.github/helpers/test-pass-check-pr.js, .github/workflows/tests-pass-check-pr.yml, .github/workflows/tests.yml, CHANGELOG.md
Related to https://github.com/supertokens/for-zenhub/issues/100
=> ci: adds timeout and auto retry of check job

README.md
Adding text to mention 3 building blocks of the architecture i.e. frontend, backend, core
=> refactor: added architecture building blocks info

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/UserRoleQueries.java, src/main/java/io/supertokens/userroles/UserRoles.java, src/main/java/io/supertokens/webserver/api/userroles/AddUserRoleAPI.java, src/main/java/io/supertokens/webserver/api/userroles/CreateRoleAPI.java, src/test/java/io/supertokens/test/userRoles/UserRolesStorageTest.java, src/test/java/io/supertokens/test/userRoles/UserRolesTest.java, src/test/java/io/supertokens/test/userRoles/api/AddUserRoleAPITest.java, src/test/java/io/supertokens/test/userRoles/api/CreateRoleAPITest.java
The plugin-interface has been updated to account for the discussion mentioned [here](https://github.com/supertokens/supertokens-core/issues/382#issuecomment-1102458937). The changes in this PR are to account for the plugin-interface updates.
- `createNewRoleOrDoNothingIfExists_Transaction` now returns a boolean, so updated the query to return a boolean on whether a row was updated or not.
- `addRoleToUser` now returns a boolean on whether a role was added to a user or the mapping already existed 
- `createNewRoleOrModifyItsPermissions` now returns a boolean on whether a new role was created
- `AddRoleToUserAPI` now returns an additional property in its response called `didUserHaveRole`
- `CreateRoleAPI` now returns an additional property in its response called `createdNewRole`
- Updates …
=> fix: updates plugin-interface functions, test fixs

src/main/java/io/supertokens/inmemorydb/queries/UserRoleQueries.java, src/main/java/io/supertokens/userroles/UserRoles.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/api/userroles/RemoveUserRoleAPI.java, src/test/java/io/supertokens/test/userRoles/UserRolesStorageTest.java, src/test/java/io/supertokens/test/userRoles/UserRolesTest.java, src/test/java/io/supertokens/test/userRoles/api/RemoveUserRoleAPITest.java
- fixs `deleteRoleForUser_Transaction` query 
- Adds the `RemoveUserRoleAPI` and its tests 
- https://github.com/supertokens/supertokens-core/pull/414
=> feat: adds RemoveUserRoleAPI

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json
Updates CHANGELOG.md, pluginInterfaceSupported.json and coreDriverInterfaceSupported.json
- https://github.com/supertokens/supertokens-core/pull/414
- none
- none
- none
=> chore: remaining checklist todos

src/test/java/io/supertokens/test/userRoles/UserRolesStorageTest.java
- Updates `testCreatingAndAddingAPermissionToARoleInTransactionAndDeletingRole` to now check that either role and permissions exist or role doesn't exist and no role permission mapping exists
- none
- none
- none
- none
=> test: updates test

src/test/java/io/supertokens/test/userRoles/UserRolesTest.java
- `createAnAuthUserAssignRolesAndDeleteUser` should not be run when using non-sql db
- none
none
none
- none
=> test: fix test to not run in non sql db

README.md
=> chore: added sattvikc to contributors

src/main/java/io/supertokens/useridmapping/UserIdMapping.java, src/main/java/io/supertokens/useridmapping/UserIdType.java, src/test/java/io/supertokens/test/Utils.java, src/test/java/io/supertokens/test/userIdMapping/UserIdMappingStorageTest.java, src/test/java/io/supertokens/test/userIdMapping/UserIdMappingTest.java
Adds core functions and tests for UserId mapping
- https://github.com/supertokens/supertokens-core/issues/463
none
- none
=> feat: (useridmapping) Adds core functions and tests

CONTRIBUTING.md
Updated docs to use the new test command 
=> docs: update test commands

src/test/java/io/supertokens/test/userIdMapping/UserIdMappingStorageTest.java
=> Userid mapping test fix

src/test/java/io/supertokens/test/userIdMapping/api/GetUserIdMappingAPITest.java, src/test/java/io/supertokens/test/userIdMapping/api/RemoveUserIdMappingAPITest.java
Adds missing checks in UserIdMapping tests
```
[io.supertokens.test.userIdMapping.api.GetUserIdMappingAPITest::testRetrieveUserIdMappingWithExternalUserIdInfoAsNull]
[io.supertokens.test.userIdMapping.api.GetUserIdMappingAPITest::testRetrieveUserIdMapping]
[io.supertokens.test.userIdMapping.api.GetUserIdMappingAPITest::testRetrievingUserIdMappingWithUnknownUserId]
[io.supertokens.test.userIdMapping.api.GetUserIdMappingAPITest::testRetrievingUserIdMappingWithoutSendingUserIdType]
[io.supertokens.test.userIdMapping.api.RemoveUserIdMappingAPITest::testDeletingAUserIdMappingWithoutSendingUserIdType]
```
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points …
=> fix: adds missing check in userIdMapping tests

CHANGELOG.md, build.gradle, config.yaml, devConfig.yaml, pluginInterfaceSupported.json, src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/cliOptions/CLIOptions.java, src/main/java/io/supertokens/config/Config.java, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/cronjobs/CronTask.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/output/Logging.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/version/Version.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/LogLevelTest.java, src/test/java/io/supertokens/test/LoggingTest.java
Implementation of a config to set log levels
- https://github.com/supertokens/supertokens-core/issues/494
Change docs to add about changing log levels
=> feat: Implementing log levels

CHANGELOG.md, src/main/java/io/supertokens/webserver/Webserver.java, src/test/java/io/supertokens/test/APITestsWithTrailingSlash.java
Core routes now support trailing slashes
=> feat: Add trailing slash support for apis

CHANGELOG.md, build.gradle
- https://github.com/supertokens/supertokens-core/issues/516
=> chore: Updates core version

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/config/SQLiteConfig.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/ThirdPartyQueries.java, src/main/java/io/supertokens/thirdparty/ThirdParty.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/api/thirdparty/CreateOrUpdateTenantMapping.java, src/main/java/io/supertokens/webserver/api/thirdparty/DeleteTenantMappingAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/ListTenantMappingConfigsAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/TenantMappingAPI.java, src/test/java/io/supertokens/test/thirdparty/api/CreateOrUpdateTenantMappingAPITest.java, src/test/java/io/supertokens/test/thirdparty/api/DeleteTenantMappingAPITest.java, src/test/java/io/supertokens/test/thirdparty/api/GetTenantMappingAPITest.java, src/test/java/io/supertokens/test/thirdparty/api/ListTenantMappingAPITest.java
=> feat: adds apis for tennat mapping

README.md
=> feat: Add docker pull stats

ee/src/test/java/io/supertokens/ee/test/api/DeleteLicenseKeyAPITest.java, ee/src/test/java/io/supertokens/ee/test/api/GetLicenseKeyAPITest.java, ee/src/test/java/io/supertokens/ee/test/api/SetLicenseKeyAPITest.java
=> chore: updates api timeouts in tests

README.md
Added my profile to the ReadMe file
N/A
=> Added profile to README.md

src/main/java/io/supertokens/cronjobs/deleteExpiredDashboardSessions/DeleteExpiredDashboardSessions.java, src/main/java/io/supertokens/cronjobs/deleteExpiredSessions/DeleteExpiredSessions.java
=> fix: adds check to cronjob

src/main/java/io/supertokens/multitenancy/Multitenancy.java, src/main/java/io/supertokens/multitenancy/MultitenancyHelper.java, src/test/java/io/supertokens/test/multitenant/ConfigTest.java
=> fix: config tests

src/main/java/io/supertokens/multitenancy/Multitenancy.java, src/main/java/io/supertokens/multitenancy/MultitenancyHelper.java, src/main/java/io/supertokens/thirdparty/InvalidProviderConfigException.java, src/main/java/io/supertokens/thirdparty/ThirdParty.java, src/test/java/io/supertokens/test/multitenant/ConfigTest.java, src/test/java/io/supertokens/test/multitenant/RandomConfigTest.java, src/test/java/io/supertokens/test/multitenant/StorageLayerTest.java, src/test/java/io/supertokens/test/multitenant/generator/ConfigGenerator.java, src/test/java/io/supertokens/test/multitenant/generator/GenerateEmailPasswordConfig.java, src/test/java/io/supertokens/test/multitenant/generator/GeneratePasswordlessConfig.java, src/test/java/io/supertokens/test/multitenant/generator/GenerateTenantConfig.java, src/test/java/io/supertokens/test/multitenant/generator/GenerateThirdPartyConfig.java, src/test/java/io/supertokens/test/multitenant/generator/GenerateThirdPartyConfig_Provider.java, src/test/java/io/supertokens/test/multitenant/generator/GenerateThirdPartyConfig_ProviderClient.java, src/test/java/io/supertokens/test/multitenant/generator/utils/JsonObjectGenerator.java, src/test/java/io/supertokens/test/multitenant/generator/utils/NullableBoolGenerator.java, src/test/java/io/supertokens/test/multitenant/generator/utils/NullableStringGenerator.java, src/test/java/io/supertokens/test/multitenant/generator/utils/URLGenerator.java
=> fix: new exceptions and tests

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/webserver/api/core/UsersAPI.java, src/main/java/io/supertokens/webserver/api/dashboard/DashboardSignInAPI.java, src/main/java/io/supertokens/webserver/api/dashboard/DashboardUserAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/UserAPI.java, src/main/java/io/supertokens/webserver/api/emailverification/GenerateEmailVerificationTokenAPI.java, src/main/java/io/supertokens/webserver/api/emailverification/RevokeAllTokensForUserAPI.java, src/main/java/io/supertokens/webserver/api/emailverification/UnverifyEmailAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/DeleteCodesAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/GetCodesAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/UserAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/GetUsersByEmailAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/SignInUpAPI.java, src/test/java/io/supertokens/test/dashboard/apis/CreateDashboardUserAPITests.java, src/test/java/io/supertokens/test/dashboard/apis/DeleteDashboardUserAPITests.java, src/test/java/io/supertokens/test/dashboard/apis/SignInAPITest.java, src/test/java/io/supertokens/test/dashboard/apis/UpdateUserAPITest.java, src/test/java/io/supertokens/test/emailpassword/api/EmailPasswordGetUserAPITest2_7.java, src/test/java/io/supertokens/test/emailpassword/api/UserPutAPITest2_8.java, src/test/java/io/supertokens/test/emailverification/api/RevokeTokenAPITest2_8.java, src/test/java/io/supertokens/test/emailverification/api/UnverifyEmailAPITest2_8.java, src/test/java/io/supertokens/test/emailverification/api/VerifyEmailAPITest2_7.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessDeleteCodesAPITest2_11.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessGetCodesAPITest2_11.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessUserGetAPITest2_11.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessUserPutAPITest2_11.java, src/test/java/io/supertokens/test/thirdparty/api/ThirdPartyGetUsersByEmailAPITest2_7.java, src/test/java/io/supertokens/test/thirdparty/api/ThirdPartySignInUpAPITest2_8.java
Adds email normalisation to all APIs that accept email as an input.
- https://github.com/supertokens/supertokens-core/issues/577
- Modified existing tests to use upper case letter in email when querying the API
- Added a few missing tests for certain APIs
None
=> Normalises email in all APIs that take email as an input

src/main/java/io/supertokens/ActiveUsers.java, src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionRemoveAPI.java, src/test/java/io/supertokens/test/ActiveUsersTest.java, src/test/java/io/supertokens/test/emailpassword/api/SignInAPITest2_7.java, src/test/java/io/supertokens/test/emailpassword/api/SignUpAPITest2_7.java, src/test/java/io/supertokens/test/passwordless/PasswordlessConsumeCodeTest.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessConsumeCodeAPITest2_11.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest2_7.java, src/test/java/io/supertokens/test/session/api/SessionAPITest2_7.java, src/test/java/io/supertokens/test/session/api/SessionAPITest2_9.java, src/test/java/io/supertokens/test/session/api/SessionRemoveAPITest2_7.java, src/test/java/io/supertokens/test/thirdparty/api/ThirdPartySignInUpAPITest2_7.java, src/test/java/io/supertokens/test/thirdparty/api/ThirdPartySignInUpAPITest2_8.java
Add tests for active users update across different API calls
=> test: Add tests for active users update across different API calls

CHANGELOG.md, src/main/java/io/supertokens/signingkeys/AccessTokenSigningKey.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/test/java/io/supertokens/test/jwt/api/JWTSigningAPITest2_19.java, src/test/java/io/supertokens/test/session/AccessTokenSigningKeyTest.java, src/test/java/io/supertokens/test/session/RegenerateTokenTest.java, src/test/java/io/supertokens/test/session/SessionTest5.java, src/test/java/io/supertokens/test/session/api/SessionAPITest2_19.java, src/test/java/io/supertokens/test/session/api/VerifySessionAPITest2_19.java
feat: rename useStaticSigningKey param and expand testing
- https://github.com/supertokens/core-driver-interface/pull/47
Updated tests
Done separately 
=> feat: rename useStaticSigningKey param and expand testing

src/main/java/io/supertokens/webserver/api/totp/CreateOrUpdateTotpDeviceAPI.java, src/main/java/io/supertokens/webserver/api/totp/GetTotpDevicesAPI.java, src/main/java/io/supertokens/webserver/api/totp/RemoveTotpDeviceAPI.java, src/main/java/io/supertokens/webserver/api/totp/VerifyTotpAPI.java, src/main/java/io/supertokens/webserver/api/totp/VerifyTotpDeviceAPI.java, src/test/java/io/supertokens/test/totp/api/CreateTotpDeviceAPITest.java, src/test/java/io/supertokens/test/totp/api/TotpUserIdMappingTest.java
refactor: Use internal supertokens user id in TOTP APIs
- https://github.com/supertokens/supertokens-core/pull/589
=> refactor: Use internal supertokens user id in TOTP APIs

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/useridmapping/UserIdMapping.java, src/test/java/io/supertokens/test/ConfigTest2_6.java, src/test/java/io/supertokens/test/FeatureFlagTest.java, src/test/java/io/supertokens/test/dashboard/DashboardTest.java, src/test/java/io/supertokens/test/totp/TOTPRecipeTest.java, src/test/java/io/supertokens/test/totp/api/VerifyTotpAPITest.java, src/test/java/io/supertokens/test/totp/api/VerifyTotpDeviceAPITest.java, src/test/java/io/supertokens/test/userIdMapping/UserIdMappingTest.java
test: Fix failing tests
- https://github.com/supertokens/supertokens-core/pull/564
=> test: Fix failing tests

CHANGELOG.md, src/main/java/io/supertokens/webserver/InputParser.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/api/core/ActiveUsersCountAPI.java, src/test/java/io/supertokens/test/ActiveUsersTest.java
Add new API and tests for counting active users
- https://github.com/supertokens/supertokens-core/pull/564
=> feat: Add new API and tests for counting active users

ee/src/test/java/io/supertokens/ee/test/EETest.java, ee/src/test/java/io/supertokens/ee/test/api/GetFeatureFlagAPITest.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/test/java/io/supertokens/test/FeatureFlagTest.java, src/test/java/io/supertokens/test/StorageLayerTest.java, src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest2_7.java, src/test/java/io/supertokens/test/session/api/SessionAPITest2_7.java, src/test/java/io/supertokens/test/session/api/SessionAPITest2_9.java, src/test/java/io/supertokens/test/session/api/SessionRemoveAPITest2_7.java, src/test/java/io/supertokens/test/totp/api/CreateTotpDeviceAPITest.java
Fix tests failing because of NoSQL DBs
- https://github.com/supertokens/supertokens-core/issues/597
=> test: Fix tests failing because of NoSQL

src/test/java/io/supertokens/test/session/api/RefreshSessionAPITest2_7.java
Fix active user test
- https://github.com/supertokens/supertokens-core/issues/597
=> test: Fix active user test

src/test/java/io/supertokens/test/ActiveUsersTest.java
Fix active user test for InmemoryDB
=> test: Fix active user test for InmemoryDB

src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/useridmapping/UserIdMapping.java, src/test/java/io/supertokens/test/authRecipe/GetUsersAPIWithUserIdMappingTest.java, src/test/java/io/supertokens/test/userIdMapping/UserIdMappingStorageTest.java, src/test/java/io/supertokens/test/userIdMapping/UserIdMappingTest.java, src/test/java/io/supertokens/test/userIdMapping/api/CreateUserIdMappingAPITest.java
=> fix: Multitenant uidmapping storage

src/test/java/io/supertokens/test/totp/TOTPStorageTest.java
Fix flaky test related to TOTP storage
=> test: Fix flaky test related to TOTP storage

src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/test/java/io/supertokens/test/emailpassword/api/MultitenantAPITest.java, src/test/java/io/supertokens/test/httpRequest/HttpRequestForTesting.java
=> fix: Multitenant email password tests

src/main/java/io/supertokens/cronjobs/deleteExpiredPasswordlessDevices/DeleteExpiredPasswordlessDevices.java, src/main/java/io/supertokens/passwordless/Passwordless.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/webserver/api/passwordless/ConsumeCodeAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/CreateCodeAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/DeleteCodeAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/DeleteCodesAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/GetCodesAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/UserAPI.java, src/test/java/io/supertokens/test/passwordless/DeleteExpiredPasswordlessDevicesTest.java, src/test/java/io/supertokens/test/passwordless/PasswordlessConsumeCodeTest.java, src/test/java/io/supertokens/test/passwordless/PasswordlessCreateCodeTest.java, src/test/java/io/supertokens/test/passwordless/PasswordlessDevicesTest.java, src/test/java/io/supertokens/test/passwordless/PasswordlessGetUserTest.java, src/test/java/io/supertokens/test/passwordless/PasswordlessRemoveCodeTest.java, src/test/java/io/supertokens/test/passwordless/PasswordlessStorageTest.java, src/test/java/io/supertokens/test/passwordless/PasswordlessUpdateUserTest.java, src/test/java/io/supertokens/test/passwordless/api/MultitenantAPITest.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessDeleteCodeAPITest2_11.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessDeleteCodesAPITest2_11.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessGetCodesAPITest2_11.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessUserGetAPITest2_11.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessUserPutAPITest2_11.java
=> fix: Multitenant API, storage and tests

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/authRecipe/GetUsersWithSearchTagsAPITest.java, src/test/java/io/supertokens/test/authRecipe/GetUsersWithSearchTagsTest.java
=> fix: fixes bug in inmemory query and updates query logic

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/thirdparty/ThirdParty.java, src/main/java/io/supertokens/webserver/api/emailpassword/ResetPasswordAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/SignInAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/UserAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/UserAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/GetUsersByEmailAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/SignInUpAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/UserAPI.java, src/test/java/io/supertokens/test/thirdparty/ThirdPartyTest.java, src/test/java/io/supertokens/test/thirdparty/ThirdPartyTest2_7.java, src/test/java/io/supertokens/test/thirdparty/api/MultitenantAPITest.java
=> fix: Multitenant thirdparty API, storage and tests

CHANGELOG.md, src/main/java/io/supertokens/inmemorydb/queries/JWTSigningQueries.java, src/main/java/io/supertokens/session/accessToken/AccessToken.java
fix: minor consistency fixes
- making jwt signing key parsing consistent between inmemory and normal db plugins
- casing fix in mongo migration script (I ended up using a casing more consistent with other DBs than with JS)
- making stored and in-token creation and expiration times consistent
- To know which one it is, run find the latest released tag (`git tag`) in …
=> fix: minor consistency fixes

src/main/java/io/supertokens/signingkeys/JWTSigningKey.java
=> fix: fix jwt signing key generation in tests

src/test/java/io/supertokens/test/session/SessionTest5.java
=> test: add a larger time margin to make test pass on CI

src/main/java/io/supertokens/jwt/JWTSigningKey.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/webserver/api/jwt/JWKSAPI.java, src/main/java/io/supertokens/webserver/api/jwt/JWTSigningAPI.java, src/test/java/io/supertokens/test/jwt/storage/JWTKeyStorageTest.java
=> fix: Multitenant jwt

src/test/java/io/supertokens/test/session/api/SessionRegenerateAPITest2_21.java, src/test/java/io/supertokens/test/session/api/SessionRegenerateAPITest2_7.java
=> test: move test and fix version number

src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/webserver/api/core/EEFeatureFlagAPI.java, src/main/java/io/supertokens/webserver/api/core/HelloAPI.java, src/main/java/io/supertokens/webserver/api/core/LicenseKeyAPI.java, src/main/java/io/supertokens/webserver/api/core/NotFoundOrHelloAPI.java, src/main/java/io/supertokens/webserver/api/core/TelemetryAPI.java, src/main/java/io/supertokens/webserver/api/core/UsersCountAPI.java, src/test/java/io/supertokens/test/authRecipe/AuthRecipeStorageTest.java, src/test/java/io/supertokens/test/authRecipe/MultitenantAPITest.java
=> fix: Multitenant Auth Recipe

ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/main/java/io/supertokens/dashboard/Dashboard.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/webserver/api/dashboard/DashboardSignInAPI.java, src/main/java/io/supertokens/webserver/api/dashboard/DashboardUserAPI.java, src/main/java/io/supertokens/webserver/api/dashboard/GetDashboardSessionsForUserAPI.java, src/main/java/io/supertokens/webserver/api/dashboard/GetDashboardUsersAPI.java, src/main/java/io/supertokens/webserver/api/dashboard/RevokeSessionAPI.java, src/main/java/io/supertokens/webserver/api/dashboard/VerifyDashboardUserSessionAPI.java, src/test/java/io/supertokens/test/dashboard/DashboardStorageTest.java, src/test/java/io/supertokens/test/dashboard/DashboardTest.java, src/test/java/io/supertokens/test/dashboard/apis/MultitenantAPITest.java, src/test/java/io/supertokens/test/dashboard/apis/SignInAPITest.java, src/test/java/io/supertokens/test/dashboard/apis/UpdateUserAPITest.java
- https://github.com/supertokens/supertokens-core/issues/546 …
=> fix: Multitenant dashboard

src/main/java/io/supertokens/totp/Totp.java, src/main/java/io/supertokens/webserver/api/totp/CreateOrUpdateTotpDeviceAPI.java, src/main/java/io/supertokens/webserver/api/totp/GetTotpDevicesAPI.java, src/main/java/io/supertokens/webserver/api/totp/RemoveTotpDeviceAPI.java, src/main/java/io/supertokens/webserver/api/totp/VerifyTotpAPI.java, src/main/java/io/supertokens/webserver/api/totp/VerifyTotpDeviceAPI.java, src/test/java/io/supertokens/test/StorageLayerTest.java, src/test/java/io/supertokens/test/totp/TOTPStorageTest.java, src/test/java/io/supertokens/test/totp/api/MultitenantAPITest.java
- https://github.com/supertokens/supertokens-core/issues/546 …
=> fix: Multitenant totp

src/main/java/io/supertokens/ResourceDistributor.java, src/main/java/io/supertokens/cliOptions/CLIOptions.java, src/main/java/io/supertokens/config/CoreConfigTestContent.java, src/main/java/io/supertokens/httpRequest/HttpRequestMocking.java, src/main/java/io/supertokens/session/Session.java, src/main/java/io/supertokens/thirdparty/ThirdParty.java
=> removes unnecessary deprecated annotation

src/main/java/io/supertokens/utils/RateLimiter.java, src/main/java/io/supertokens/webserver/api/core/HelloAPI.java, src/main/java/io/supertokens/webserver/api/core/NotFoundOrHelloAPI.java, src/test/java/io/supertokens/test/TestHelloAPIRateLimiting.java
=> fix: Rate limiting hello

ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/main/java/io/supertokens/multitenancy/Multitenancy.java, src/main/java/io/supertokens/webserver/api/multitenancy/thirdparty/CreateOrUpdateThirdPartyConfigAPI.java, src/test/java/io/supertokens/test/FeatureFlagTest.java
- Feature flag check on base tenant instead of source tenant
- Check for multitenancy in create or update thirdparty config
- Fixed totp stats to loop through all storages
- Added multitenancy stats
latest branch (`git branch --all`) whose …
=> fix: multitenancy stats

ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/main/java/io/supertokens/emailpassword/EmailPassword.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java, src/main/java/io/supertokens/inmemorydb/queries/ThirdPartyQueries.java, src/main/java/io/supertokens/passwordless/Passwordless.java, src/main/java/io/supertokens/thirdparty/ThirdParty.java, src/test/java/io/supertokens/test/FeatureFlagTest.java, src/test/java/io/supertokens/test/emailpassword/EmailPasswordTest.java, src/test/java/io/supertokens/test/emailpassword/api/EmailPasswordGetUserAPITest2_7.java, src/test/java/io/supertokens/test/emailpassword/api/ImportUserWithPasswordHashAPITest.java, src/test/java/io/supertokens/test/emailpassword/api/MultitenantAPITest.java, src/test/java/io/supertokens/test/emailpassword/api/SignInAPITest2_7.java, src/test/java/io/supertokens/test/emailpassword/api/SignUpAPITest2_7.java, src/test/java/io/supertokens/test/multitenant/api/TestMultitenancyAPIHelper.java, src/test/java/io/supertokens/test/multitenant/api/TestTenantUserAssociation.java, src/test/java/io/supertokens/test/passwordless/PasswordlessStorageTest.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessConsumeCodeAPITest2_11.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessUserGetAPITest2_11.java, src/test/java/io/supertokens/test/passwordless/api/PasswordlessUserPutAPITest2_11.java, src/test/java/io/supertokens/test/thirdparty/ThirdPartyTest.java, src/test/java/io/supertokens/test/thirdparty/ThirdPartyTest2_7.java
=> fix: Tenantid in userobjects

src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/signingkeys/JWTSigningKey.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/IpAllowDenyRegexTest.java
=> fix: Ip filter per tenant

src/main/java/io/supertokens/output/Logging.java
Making console log not include tenant info for base tenant. Final output for 10 tenants:
```
Loading supertokens config.
Completed config.yaml loading.
Loading storage layer.
Loading supertokens version.yaml file.
Setting up PostgreSQL connection pool.
Started SuperTokens on localhost:3567 with PID: 5061
```
- To know which one it is, run find the latest released …
=> fix: Startup log

src/main/java/io/supertokens/config/CoreConfig.java, src/test/java/io/supertokens/test/multitenant/ConfigTest.java
=> fix: Apikey per app

src/test/java/io/supertokens/test/multitenant/ConfigTest.java
=> test: Config normalisation test

src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/multitenancy/Multitenancy.java, src/test/java/io/supertokens/test/multitenant/api/TestTenantUserAssociation.java, src/test/java/io/supertokens/test/userIdMapping/UserIdMappingTest.java
=> fix: delete non auth user in deleteUserIdFromTenantId

src/main/java/io/supertokens/thirdparty/ThirdParty.java, src/test/java/io/supertokens/test/multitenant/TestProviderEquality.java
- Test to verify Provider class equality along with other related classes
- Removed validations for Active Directory and Okta
- If no such branch exists, then create …
=> fix: thirdparty related tests

src/test/java/io/supertokens/test/authRecipe/UserPaginationTest.java, src/test/java/io/supertokens/test/multitenant/api/TestMultitenancyAPIHelper.java
Test user list with pagination for different tenants and include recipe ids.
- If no such branch exists, then create one from the latest released …
=> fix: user pagination test

src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/featureflag/FeatureFlag.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/session/refreshToken/RefreshTokenKey.java, src/main/java/io/supertokens/signingkeys/AccessTokenSigningKey.java, src/main/java/io/supertokens/signingkeys/JWTSigningKey.java, src/main/java/io/supertokens/signingkeys/SigningKeys.java, src/test/java/io/supertokens/test/multitenant/SigningKeysTest.java
=> fix: clean up init keys

src/main/java/io/supertokens/signingkeys/AccessTokenSigningKey.java, src/main/java/io/supertokens/signingkeys/JWTSigningKey.java, src/test/java/io/supertokens/test/session/AccessTokenSigningKeyTest.java, src/test/java/io/supertokens/test/session/DeleteExpiredAccessTokenSigningKeysTest.java
=> fix: removed isTesting check in prod code

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/test/java/io/supertokens/test/CronjobTest.java, src/test/java/io/supertokens/test/multitenant/StorageLayerTest.java
=> fix: fixed missing log

src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/session/Session.java
=> fix: fixing merge issues

src/main/java/io/supertokens/session/Session.java, src/main/java/io/supertokens/session/accessToken/AccessToken.java, src/main/java/io/supertokens/session/jwt/JWT.java, src/main/java/io/supertokens/webserver/api/session/JWTDataAPI.java, src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionDataAPI.java, src/test/java/io/supertokens/test/InMemoryDBTest.java, src/test/java/io/supertokens/test/session/AccessTokenTest.java, src/test/java/io/supertokens/test/session/JWTDataTest.java, src/test/java/io/supertokens/test/session/RegenerateTokenTest.java, src/test/java/io/supertokens/test/session/SessionGetJWTDataTest.java, src/test/java/io/supertokens/test/session/SessionGetSessionDataTest.java, src/test/java/io/supertokens/test/session/SessionTest1.java, src/test/java/io/supertokens/test/session/SessionTest2.java, src/test/java/io/supertokens/test/session/SessionTest3.java, src/test/java/io/supertokens/test/session/SessionTest4.java, src/test/java/io/supertokens/test/session/SessionTest5.java, src/test/java/io/supertokens/test/session/api/VerifySessionAPITest2_21.java, src/test/java/io/supertokens/test/session/api/VerifySessionAPITest2_22.java, src/test/java/io/supertokens/test/session/api/VersionTest.java
=> fix: session v4

CHANGELOG.md
=> fix: Postgres migration

src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/test/java/io/supertokens/test/multitenant/api/TestTenantUserAssociation.java, src/test/java/io/supertokens/test/userIdMapping/UserIdMappingTest.java
=> fix: fixed tests for active user storage

CHANGELOG.md, src/main/java/io/supertokens/dashboard/Dashboard.java, src/main/java/io/supertokens/webserver/api/dashboard/VerifyDashboardUserSessionAPI.java, src/test/java/io/supertokens/test/dashboard/apis/VerifySessionAPITest.java
- Changes the response of the verify API for the dashboard recipe
- 
Updated existing tests
NA
=> refactor: Add email to the response of Dashboard verify session API

src/test/java/io/supertokens/test/oauth2/StorageTests.java
Added missing and new tests for create and get methods of oauth2client & oauth2scope tables psql plugin method implementations.
- https://github.com/supertokens/supertokens-core/issues/582
- If no such branch …
=> test: Added missing and new tests for create and get methods of oauth2client & oauth2scope

CHANGELOG.md, config.yaml, devConfig.yaml, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/CDIVersionTest.java, src/test/java/io/supertokens/test/multitenant/api/TestTenantIdIsNotPresentForOlderCDI.java
- Repeatable migration script (PostgreSQL)
- Added `supertokens_default_cdi_version` config
- Updated changelog …
=> fix: changes for release

src/test/java/io/supertokens/test/multitenant/ConfigTest.java
=> fix: test fix for mongo

src/test/java/io/supertokens/test/httpRequest/HttpRequestForTesting.java, src/test/java/io/supertokens/test/multitenant/StorageLayerTest.java, src/test/java/io/supertokens/test/totp/TOTPRecipeTest.java, src/test/java/io/supertokens/test/totp/TOTPStorageTest.java
=> fix: test fixes

src/main/java/io/supertokens/storageLayer/StorageLayer.java
=> fix: delete all info on unique storages

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/test/java/io/supertokens/test/multitenant/TestAppData.java
=> fix: appid fkey test

config.yaml, devConfig.yaml, src/main/java/io/supertokens/config/Config.java, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/config/annotations/ConfigYamlOnly.java, src/main/java/io/supertokens/config/annotations/IgnoreForAnnotationCheck.java, src/main/java/io/supertokens/config/annotations/NotConflictingInApp.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/test/java/io/supertokens/test/multitenant/ConfigTest.java, src/test/java/io/supertokens/test/multitenant/StorageLayerTest.java, src/test/java/io/supertokens/test/multitenant/api/TestApp.java, src/test/java/io/supertokens/test/multitenant/api/TestTenant.java
=> fix: annotations for CoreConfig + tests and couple of tests from checklist

devConfig.yaml, src/test/java/io/supertokens/test/CronjobTest.java
=> fix: test cron task functions

src/main/java/io/supertokens/output/Logging.java, src/test/java/io/supertokens/test/multitenant/LoadTest.java
=> fixes issue with logging memory leak

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/session/Session.java, src/main/java/io/supertokens/webserver/InputParser.java, src/main/java/io/supertokens/webserver/api/multitenancy/thirdparty/CreateOrUpdateThirdPartyConfigAPI.java, src/main/java/io/supertokens/webserver/api/session/JWTDataAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionDataAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionRegenerateAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionRemoveAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionUserAPI.java, src/test/java/io/supertokens/test/multitenant/api/TestMultitenancyAPIHelper.java, src/test/java/io/supertokens/test/session/api/MultitenantAPITest.java, src/test/java/io/supertokens/test/session/api/SessionRemoveAPITest2_7.java
- Normalizing thirdParty config as it may contain nulls while parsing from json.
- Making session APIs app specific
- Adding flags to fetch / revoke user session across all tenants
latest branch (`git branch --all`) whose `X.Y` is greater than the latest …
=> fix: core fixes during SDK dev

CHANGELOG.md, ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/main/java/io/supertokens/cronjobs/telemetry/Telemetry.java, src/test/java/io/supertokens/test/FeatureFlagTest.java, src/test/java/io/supertokens/test/TelemetryTest.java
=> fix: telemetry and stats fix

src/main/java/io/supertokens/multitenancy/Multitenancy.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/multitenant/ConfigTest.java, src/test/java/io/supertokens/test/multitenant/api/TestPermissionChecks.java
=> fix: protected config and message fixes

CHANGELOG.md, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/SuperTokensSaaSSecretTest.java
- https://github.com/supertokens/supertokens-node/pull/471
=> fix: logging for APIKeyUnauthorisedException

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/output/Logging.java
Tenant prefix in stack trace log (error log)
Manually tested
=> fix: tenant prefix in stack trace log

src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/test/java/io/supertokens/test/emailpassword/api/MultitenantAPITest.java
=> fix: null pointer issue for user that belongs to no tenant

src/test/java/io/supertokens/test/multitenant/api/TestMultitenancyAPIHelper.java
=> fix: update timeout for add license

src/main/java/io/supertokens/session/accessToken/AccessToken.java, src/main/java/io/supertokens/utils/Utils.java, src/test/java/io/supertokens/test/session/AccessTokenTest.java, src/test/java/io/supertokens/test/session/api/SessionRegenerateAPITest2_21.java
=> more fixes

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/webserver/Utils.java, src/test/java/io/supertokens/test/multitenant/api/TestPermissionChecks.java
=> fix: cud validation

src/main/java/io/supertokens/webserver/api/core/UsersAPI.java, src/test/java/io/supertokens/test/accountlinking/api/UserPaginationTest.java
=> fix: user pagination tests

src/main/java/io/supertokens/ActiveUsers.java, src/main/java/io/supertokens/webserver/api/accountlinking/LinkAccountsAPI.java, src/test/java/io/supertokens/test/accountlinking/api/ActiveUserTest.java
=> fix: remove active user of recipe user when linked

src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/main/java/io/supertokens/emailpassword/EmailPassword.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/multitenancy/Multitenancy.java, src/main/java/io/supertokens/passwordless/Passwordless.java, src/main/java/io/supertokens/thirdparty/ThirdParty.java, src/test/java/io/supertokens/test/accountlinking/MultitenantTest.java, src/test/java/io/supertokens/test/accountlinking/UnlinkAccountsTest.java, src/test/java/io/supertokens/test/accountlinking/api/TestRecipeUserIdInSignInUpAPIs.java, src/test/java/io/supertokens/test/multitenant/api/TestMultitenancyAPIHelper.java, src/test/java/io/supertokens/test/multitenant/api/TestTenantUserAssociation.java
=> fix: multitenant user association with account linking

CHANGELOG.md
=> fix: updated migration script

ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/test/java/io/supertokens/test/FeatureFlagTest.java
=> fix: account linking stats

src/main/java/io/supertokens/emailpassword/EmailPassword.java, src/test/java/io/supertokens/test/accountlinking/MultitenantTest.java
=> fix: ep login issues

src/main/java/io/supertokens/webserver/api/multitenancy/AssociateUserToTenantAPI.java, src/main/java/io/supertokens/webserver/api/multitenancy/DisassociateUserFromTenant.java
=> fix: rename userId to recipeUserId

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/inmemorydb/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java, src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java, src/main/java/io/supertokens/inmemorydb/queries/ThirdPartyQueries.java, src/main/java/io/supertokens/inmemorydb/queries/UserMetadataQueries.java, src/main/java/io/supertokens/inmemorydb/queries/UserRoleQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/136
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/138 …
=> fix: function changes

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/143
=> fix: adds recipe user id in session

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java, src/main/java/io/supertokens/inmemorydb/queries/ThirdPartyQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/145
=> fix: user pagination

src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/152
=> fix: index updates

src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/153
=> fix: fkey constraint

src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java, src/main/java/io/supertokens/inmemorydb/queries/ThirdPartyQueries.java
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/155
- https://github.com/supertokens/supertokens-postgresql-plugin/pull/156 …
=> Al tenant association fix

src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/inmemorydb/queries/DashboardQueries.java, src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/inmemorydb/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/MultitenancyQueries.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java, src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java, src/main/java/io/supertokens/inmemorydb/queries/ThirdPartyQueries.java, src/main/java/io/supertokens/inmemorydb/queries/UserIdMappingQueries.java, src/main/java/io/supertokens/inmemorydb/queries/UserMetadataQueries.java, src/main/java/io/supertokens/inmemorydb/queries/UserRolesQueries.java, src/main/java/io/supertokens/useridmapping/UserIdMapping.java, src/test/java/io/supertokens/test/AuthRecipesParallelTest.java, src/test/java/io/supertokens/test/accountlinking/CreatePrimaryUserTest.java, src/test/java/io/supertokens/test/accountlinking/LinkAccountsTest.java, src/test/java/io/supertokens/test/accountlinking/api/CreatePrimaryUserAPITest.java, src/test/java/io/supertokens/test/accountlinking/api/LinkAccountsAPITest.java, src/test/java/io/supertokens/test/authRecipe/DeleteUserAPIWithUserIdMappingTest.java, src/test/java/io/supertokens/test/multitenant/api/TestMultitenancyAPIHelper.java
=> fix: tests

ee/src/test/java/io/supertokens/ee/test/TestMultitenancyStats.java
=> fix: test fix

src/main/java/io/supertokens/session/Session.java, src/test/java/io/supertokens/test/AuthRecipesParallelTest.java, src/test/java/io/supertokens/test/SuperTokensSaaSSecretTest.java, src/test/java/io/supertokens/test/accountlinking/CreatePrimaryUserTest.java, src/test/java/io/supertokens/test/accountlinking/GetUserByAccountInfoTest.java, src/test/java/io/supertokens/test/accountlinking/GetUserByIdTest.java, src/test/java/io/supertokens/test/accountlinking/MultitenantTest.java, src/test/java/io/supertokens/test/accountlinking/api/CanCreatePrimaryUserAPITest.java, src/test/java/io/supertokens/test/accountlinking/api/CanLinkAccountsAPITest.java, src/test/java/io/supertokens/test/accountlinking/api/CreatePrimaryUserAPITest.java, src/test/java/io/supertokens/test/accountlinking/api/GetUserByAccountInfoTest.java, src/test/java/io/supertokens/test/accountlinking/api/GetUserByIdTest.java, src/test/java/io/supertokens/test/accountlinking/api/LinkAccountsAPITest.java, src/test/java/io/supertokens/test/accountlinking/api/UserPaginationTest.java, src/test/java/io/supertokens/test/passwordless/api/EmailVerificationTest.java, src/test/java/io/supertokens/test/thirdparty/api/EmailVerificationTest.java
=> fix: fixes for mongo plugin

src/main/java/io/supertokens/ProcessState.java, src/test/java/io/supertokens/test/accountlinking/TimeJoinedTest.java, src/test/java/io/supertokens/test/accountlinking/UserIdMappingTest.java, src/test/java/io/supertokens/test/accountlinking/UserSearchTest.java
=> fix: mongo fixes

src/main/java/io/supertokens/inmemorydb/queries/UserRolesQueries.java
=> fix: inmemory test fix

README.md
=> fix: merge 7.0

src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/MfaQueries.java, src/test/java/io/supertokens/test/FeatureFlagTest.java, src/test/java/io/supertokens/test/mfa/MfaLicenseTest.java, src/test/java/io/supertokens/test/mfa/MfaStorageTest.java, src/test/java/io/supertokens/test/mfa/MfaTestBase.java, src/test/java/io/supertokens/test/totp/TOTPRecipeTest.java
=> fix: flaky tests

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/cronjobs/CronTask.java, src/main/java/io/supertokens/cronjobs/Cronjobs.java, src/main/java/io/supertokens/multitenancy/MultitenancyHelper.java, src/test/java/io/supertokens/test/CronjobTest.java
=> fix: cronjobs per app issue

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/cronjobs/CronTask.java, src/main/java/io/supertokens/cronjobs/Cronjobs.java, src/main/java/io/supertokens/multitenancy/MultitenancyHelper.java, src/test/java/io/supertokens/test/CronjobTest.java
=> fix: crontask per app issue

.circleci/doTests.sh
=> fix: skip postgres tests

CHANGELOG.md, build.gradle, src/test/java/io/supertokens/test/multitenant/RandomConfigTest.java
=> fix: tenant config test

src/test/java/io/supertokens/test/multitenant/api/TestMultitenancyAPIHelper.java, src/test/java/io/supertokens/test/multitenant/api/TestThirdPartyProvider.java
=> test: thirdparty json

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/inmemorydb/queries/UserIdMappingQueries.java, src/test/java/io/supertokens/test/accountlinking/api/EmailVerificationTest.java
- https://github.com/supertokens/supertokens-core/issues/872
=> fix: test email verified with user id mapping

ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/SignInAPI.java, src/main/java/io/supertokens/webserver/api/emailpassword/SignUpAPI.java, src/main/java/io/supertokens/webserver/api/passwordless/ConsumeCodeAPI.java, src/main/java/io/supertokens/webserver/api/session/RefreshSessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionAPI.java, src/main/java/io/supertokens/webserver/api/session/SessionRemoveAPI.java, src/main/java/io/supertokens/webserver/api/thirdparty/SignInUpAPI.java, src/test/java/io/supertokens/test/ActiveUsersTest.java, src/test/java/io/supertokens/test/FeatureFlagTest.java
- https://github.com/supertokens/supertokens-core/pull/651 …
=> fix: mfa stats

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/webserver/RequestStats.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/main/java/io/supertokens/webserver/api/core/RequestStatsAPI.java, src/test/java/io/supertokens/test/RequestStatsTest.java
Collects average and peak RPS and saves in memory for last 1 day.
=> fix: request stats

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/webserver/RequestStats.java, src/main/java/io/supertokens/webserver/Webserver.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/main/java/io/supertokens/webserver/api/core/RequestStatsAPI.java, src/test/java/io/supertokens/test/RequestStatsTest.java
=> fix: requests stats

CHANGELOG.md, build.gradle, src/test/java/io/supertokens/test/accountlinking/TestGetUserSpeed.java
Adds a test to ensure query speed is good for user creation, linking and get by userId
- https://github.com/supertokens/supertokens-core/issues/887
- If no such branch exists, then create one from the latest …
=> test: user query speeds

CHANGELOG.md, build.gradle, src/test/java/io/supertokens/test/accountlinking/TestGetUserSpeed.java
Using parallel instead of serial
=> fix: updates user query speed test

CHANGELOG.md, build.gradle, src/test/java/io/supertokens/test/accountlinking/api/UserPaginationTest.java
=> fix: adds test for user pagination from old version

CHANGELOG.md, src/main/java/io/supertokens/storageLayer/StorageLayer.java
=> fix: Connection pool issue

src/test/java/io/supertokens/test/AuthRecipesParallelTest.java, src/test/java/io/supertokens/test/accountlinking/TestGetUserSpeed.java
=> fix: CICD tests

src/test/java/io/supertokens/test/StorageLayerTest.java, src/test/java/io/supertokens/test/TelemetryTest.java
=> fix: Cicd tests fix

build.gradle, cli/build.gradle, ee/build.gradle, implementationDependencies.json
=> fix: dependencies

ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, ee/src/test/java/io/supertokens/ee/test/api/GetFeatureFlagAPITest.java, src/main/java/io/supertokens/cronjobs/telemetry/Telemetry.java, src/test/java/io/supertokens/test/FeatureFlagTest.java, src/test/java/io/supertokens/test/TelemetryTest.java, src/test/java/io/supertokens/test/dashboard/DashboardTest.java
=> fix: 31 days of mau

ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/main/java/io/supertokens/cronjobs/telemetry/Telemetry.java
=> fix: MAU computation

pluginInterfaceSupported.json
=> fix: plugin interface version

CHANGELOG.md, src/test/java/io/supertokens/test/totp/api/VerifyTotpAPITest.java
=> fix: changelog

CHANGELOG.md, src/test/java/io/supertokens/test/authRecipe/UserPaginationTest.java
=> fix: pagination

src/test/java/io/supertokens/test/AuthRecipeTest.java
=> fix: random pagination test

src/test/java/io/supertokens/test/accountlinking/api/ActiveUserTest.java
=> fix: cicd test

CHANGELOG.md, build.gradle, cli/build.gradle, cli/implementationDependencies.json, ee/build.gradle, ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, ee/src/test/java/io/supertokens/ee/test/EETest.java, ee/src/test/java/io/supertokens/ee/test/api/GetFeatureFlagAPITest.java, implementationDependencies.json, src/main/java/io/supertokens/cronjobs/telemetry/Telemetry.java, src/test/java/io/supertokens/test/AuthRecipeTest.java, src/test/java/io/supertokens/test/FeatureFlagTest.java, src/test/java/io/supertokens/test/StorageLayerTest.java, src/test/java/io/supertokens/test/TelemetryTest.java, src/test/java/io/supertokens/test/dashboard/DashboardTest.java
=> fix: backports to core 5.0

build.gradle, implementationDependencies.json
=> fix: sqlite version

src/main/java/io/supertokens/Main.java
=> fix: fix for sqlite

README.md
Added Viraj Kanwade to contributors as mentioned by @rishabhpoddar  https://github.com/supertokens/supertokens-python/issues/503#issuecomment-2117832975
=> docs(README.md): Added Viraj Kanwade to contributors

README.md
Fixed typo in contributors table
=> fix(README.md): fix typo in contributors

CHANGELOG.md
=> fix: mysql migration for multitenancy

README.md
Added Anurag Srivastava to contributors list as mentioned by @porcellus [supporting esm import supertokens-node](https://github.com/supertokens/supertokens-node/pull/824#issuecomment-2155267983)
=> docs(README.md): Added Anurag Srivastava to contributors

src/main/java/io/supertokens/cronjobs/telemetry/Telemetry.java
=> fix: telemetry for non sql

.circleci/doTests.sh
=> fix: gradle.properties in tests

src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/config/annotations/HideFromDashboard.java
=> fix: HideFromDashboard annotation

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/webserver/PathRouter.java, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/main/java/io/supertokens/webserver/api/core/NotFoundOrHelloAPI.java, src/test/java/io/supertokens/test/HelloAPITest.java
- https://github.com/supertokens/supertokens-core/issues/1021
- Updated tests
the user as well if `deleteUserIdMappingToo` is false.
=> fix: pathrouter for tenant id stop words

CHANGELOG.md, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/PathRouterTest.java
=> fix: 500 error to return actual message

CHANGELOG.md, build.gradle, ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/main/java/io/supertokens/featureflag/EE_FEATURES.java
=> feat: add security feature

src/test/java/io/supertokens/test/FeatureFlagTest.java
=> fix: feature test fix

CHANGELOG.md, build.gradle, ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/test/java/io/supertokens/test/FeatureFlagTest.java
Removing some of the stats that consume high CPU …
=> fix: stats

src/test/java/io/supertokens/test/CLIOptionsTest.java
=> fix: failing cli options test

src/test/java/io/supertokens/test/DotStartedFileTest.java, src/test/java/io/supertokens/test/WebserverTest.java
=> fix: fix failing dotfile and webserver test

src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/cronjobs/cleanupOAuthSessionsAndChallenges/CleanupOAuthSessionsAndChallenges.java, src/test/java/io/supertokens/test/CronjobTest.java, src/test/java/io/supertokens/test/multitenant/TestAppData.java
=> test: fix ci test failures and naming consistency

src/test/java/io/supertokens/test/oauth/api/OAuthAPIHelper.java
=> test: try and improve flaky tests

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/webserver/WebserverAPI.java, src/test/java/io/supertokens/test/PathRouterTest.java, src/test/java/io/supertokens/test/emailpassword/api/ImportUserWithPasswordHashAPITest.java
=> fix: 500 error message

pluginInterfaceSupported.json
=> fix: plugin version

src/main/java/io/supertokens/bulkimport/BulkImport.java
=> fix: build fix

src/main/java/io/supertokens/bulkimport/BulkImport.java
=> fix: code cleanup

.circleci/Dockerfile-ubuntu22, .circleci/config.yml, .circleci/testCli.sh
MySQL 5.7 -> 8
PostgreSQL 9.5 -> 13
These are the currently supported versions by their maintainers.
The image `tamassupertokens/supertokens_core_testing` is replacing the `rishabhpoddar/supertokens_core_testing` image, as I can't update an image in Rishabh's docker repo. The mentioned image is built from the `Dockerfile-ubuntu22`, which is also in this PR.
config …
=> feat!: upgrade mysql and postgresql versions on cicd

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/inmemorydb/queries/SessionQueries.java
=> fix: version update

src/test/java/io/supertokens/test/oauth/api/OAuthAPIHelper.java
=> fix: ignore reset error

src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/inmemorydb/config/SQLiteConfig.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/WebAuthNQueries.java, src/main/java/io/supertokens/webauthn/WebAuthN.java, src/main/java/io/supertokens/webauthn/exception/InvalidTokenException.java, src/main/java/io/supertokens/webauthn/exception/WebAuthNEmailNotFoundException.java, src/main/java/io/supertokens/webserver/api/webauthn/ConsumeRecoverAccountTokenAPI.java, src/main/java/io/supertokens/webserver/api/webauthn/GenerateRecoverAccountTokenAPI.java, src/main/java/io/supertokens/webserver/api/webauthn/GetUserFromRecoverAccountTokenAPI.java
=> feat: webauthn - account recovery

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/PasswordlessQueries.java, src/main/java/io/supertokens/inmemorydb/queries/ThirdPartyQueries.java, src/main/java/io/supertokens/webserver/WebserverAPI.java
- https://github.com/supertokens/supertokens-core/issues/1087 …
=> fix: slow queries for account linking

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java
=> fix: user search

.github/helpers/Dockerfile, .github/workflows/publish-dev-docker.yml
=> backport: ci changes from webauthn version

.github/workflows/publish-dev-docker.yml
=> ci: fix docker image push

CHANGELOG.md, src/main/java/io/supertokens/output/CustomLayout.java, src/main/java/io/supertokens/output/Logging.java
=> fix: structured logging

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/config/Config.java, src/main/java/io/supertokens/featureflag/FeatureFlag.java, src/main/java/io/supertokens/output/CustomLayout.java, src/main/java/io/supertokens/output/Logging.java, src/main/java/io/supertokens/session/refreshToken/RefreshTokenKey.java, src/main/java/io/supertokens/signingkeys/AccessTokenSigningKey.java, src/main/java/io/supertokens/signingkeys/JWTSigningKey.java, src/main/java/io/supertokens/signingkeys/SigningKeys.java
=> fix: resource reloading and structured logging

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/bulkimport/BulkImport.java, src/main/java/io/supertokens/inmemorydb/QueryExecutorTemplate.java, src/test/java/io/supertokens/test/bulkimport/apis/ImportUserTest.java
- Fixes `StorageTransactionLogicException` in bulk import when not using userRoles and totpDevices in import json.
- MFA only required in Bulk Import if it's used in input data
- To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find …
=> fix: fixes StorageTransactionLogicException when bulk importing

build.gradle, implementationDependencies.json
=> fix: webauthn dependency update

src/main/java/io/supertokens/webserver/api/webauthn/GetUserFromRecoverAccountTokenAPI.java, src/test/java/io/supertokens/test/webauthn/RecoverAccountFlowTest.java, src/test/java/io/supertokens/test/webauthn/Utils.java, src/test/java/io/supertokens/test/webauthn/api/TestConsumeRecoverAccountTokenAPI_5_3.java, src/test/java/io/supertokens/test/webauthn/api/TestGenerateRecoverAccountTokenAPI_5_3.java, src/test/java/io/supertokens/test/webauthn/api/TestGetUserFromRecoverAccountTokenAPI_5_3.java
=> test: more webauthn tests

src/test/java/io/supertokens/test/CronjobTest.java
=> fix: bulk migration test fix

src/main/java/io/supertokens/config/CoreConfig.java
=> fix: config description space

CHANGELOG.md, src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/main/java/io/supertokens/authRecipe/exception/BulkImportRecipeUserIdAlreadyLinkedWithAnotherPrimaryUserIdException.java, src/main/java/io/supertokens/bulkimport/BulkImport.java, src/main/java/io/supertokens/bulkimport/BulkImportUserUtils.java, src/main/java/io/supertokens/cronjobs/bulkimport/ProcessBulkUsersImportWorker.java, src/test/java/io/supertokens/test/bulkimport/BulkImportFlowTest.java, src/test/java/io/supertokens/test/bulkimport/BulkImportTest.java, src/test/java/io/supertokens/test/bulkimport/BulkImportTestUtils.java, src/test/java/io/supertokens/test/bulkimport/apis/ImportUserTest.java
Bulk Migration's account linking and primary user creations changes so it avoids loading the same data multiple times from the DB and also avoids loading already known data. …
=> fix: bulk migration account linking

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/authRecipe/AuthRecipe.java, src/main/java/io/supertokens/authRecipe/exception/BulkImportRecipeUserIdAlreadyLinkedWithAnotherPrimaryUserIdException.java, src/main/java/io/supertokens/bulkimport/BulkImport.java, src/main/java/io/supertokens/bulkimport/BulkImportUserUtils.java, src/main/java/io/supertokens/cronjobs/bulkimport/ProcessBulkUsersImportWorker.java, src/main/java/io/supertokens/webserver/api/bulkimport/BulkImportAPI.java, src/main/java/io/supertokens/webserver/api/bulkimport/ImportUserAPI.java, src/test/java/io/supertokens/test/bulkimport/BulkImportFlowTest.java, src/test/java/io/supertokens/test/bulkimport/BulkImportTest.java, src/test/java/io/supertokens/test/bulkimport/BulkImportTestUtils.java, src/test/java/io/supertokens/test/bulkimport/ProcessBulkImportUsersCronJobTest.java, src/test/java/io/supertokens/test/bulkimport/apis/AddBulkImportUsersTest.java, src/test/java/io/supertokens/test/bulkimport/apis/ImportUserTest.java
Bulk migration user upload now returns the ids of the users.
- If no such branch …
=> feat: bulk migration return userids

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/cronjobs/bulkimport/ProcessBulkImportUsers.java, src/test/java/io/supertokens/test/bulkimport/BulkImportFlowTest.java
Adds debug logging to the bulk migration process …
=> fix: bulk migration debug logs

src/test/java/io/supertokens/test/bulkimport/BulkImportTest.java
=> fix: bulk migration webauthn user tests

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/bulkimport/BulkImport.java, src/main/java/io/supertokens/cronjobs/bulkimport/ProcessBulkImportUsers.java, src/main/java/io/supertokens/cronjobs/bulkimport/ProcessBulkUsersImportWorker.java, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/UserRolesQueries.java, src/test/java/io/supertokens/test/bulkimport/BulkImportFlowTest.java, src/test/java/io/supertokens/test/bulkimport/ProcessBulkImportUsersCronJobTest.java
=> fix: bulk migration account linking test fixes

src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java
=> fix: user roles index

build.gradle, implementationDependencies.json
By requiring to manage a json file _by hand_ for the release's dependencies, we are setting ourselves up for failure. For pinning exact versions, we already use the `build.gradle` file. From that this `implementationDependencies.json` could be generated if really necessary - with the right content and exact versions.. (By right content I mean the dependencies of a dependency..)
Anyway, now I did it _by hand_. I really don't want to do this again. …
=> fix: dependency versions

CHANGELOG.md, build.gradle
=> fix: version bump

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/bulkimport/BulkImport.java, src/test/java/io/supertokens/test/bulkimport/BulkImportTestUtils.java, src/test/java/io/supertokens/test/bulkimport/ProcessBulkImportUsersCronJobTest.java
Fixes bulk migration user roles association when there is no externalId
- If no such …
=> fix: bulk migration user roles association fix when there is no externalId

.github/workflows/add-dev-tag.yml, .github/workflows/dev-tag.yml
=> fix: workflows

.github/workflows/do-release.yml, .github/workflows/publish-dev-docker.yml, .github/workflows/unit-test.yml
=> fix: release workflows

CHANGELOG.md, build.gradle
Upgrades tomcat_embed from 11.0.5 to 11.0.6 because of found CVE
- If no such branch …
=> fix: upgrade tomcat to 11.0.6

.github/workflows/dev-tag.yml, CHANGELOG.md, build.gradle, ee/build.gradle
=> fix: logback vulnerability

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/inmemorydb/queries/GeneralQueries.java, src/main/java/io/supertokens/inmemorydb/queries/WebAuthNQueries.java, src/test/java/io/supertokens/test/AuthRecipeTest.java, src/test/java/io/supertokens/test/TestServiceUtils.java
=> fix: getUserByAccountInfo fix to consider tenantId instead of appId

CHANGELOG.md, build.gradle, config.yaml, devConfig.yaml, implementationDependencies.json, src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/output/Logging.java, src/main/java/io/supertokens/telemetry/TelemetryProvider.java, src/test/java/io/supertokens/test/Utils.java
fix: add implementationDependencies.json dependencies
chore: build version and changelog
fix: add missing config and devConfig entries
fix: remove accidentally merged lines
- To know which one it is, run find the latest released tag (`git tag`) in the …
=> backport: logs to otel 

CHANGELOG.md, src/main/java/io/supertokens/Main.java, src/main/java/io/supertokens/config/Config.java, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/config/annotations/EnvName.java, src/main/java/io/supertokens/inmemorydb/Start.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/utils/ConfigMapper.java, src/test/java/io/supertokens/test/ConfigMapperTest.java, src/test/java/io/supertokens/test/EnvConfigTest.java
=> feat: load config from env

CHANGELOG.md, config.yaml, devConfig.yaml, ee/src/main/java/io/supertokens/ee/EEFeatureFlag.java, src/main/java/io/supertokens/config/CoreConfig.java, src/main/java/io/supertokens/cronjobs/telemetry/Telemetry.java, src/main/java/io/supertokens/storageLayer/StorageLayer.java, src/main/java/io/supertokens/telemetry/TelemetryProvider.java, src/main/java/io/supertokens/version/VersionFile.java
=> fix: test slowness due to invalid otel url

CHANGELOG.md, build.gradle
=> fix: version bump for backport release
